# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-09 08:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_post_is_markdown'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_markdown',
            field=models.BooleanField(default=True, verbose_name='\u4f7f\u7528markdown'),
        ),
    ]
