# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-07-12 04:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180307_1644'),
        ('blog', '0005_auto_20180310_1549'),
    ]

    operations = [
    ]
