# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-07-12 04:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0003_auto_20180307_1644'),
        ('comment', '0003_auto_20180307_2004'),
    ]

    operations = [
    ]
